name: Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ github.token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: "build:github"
        env:
          REACT_APP_GIT_COMMIT_HASH: ${{ github.sha }}

      - name: Upload Build Artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: taskunifier-app-build
          path: build

      - name: Upload Linux Artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: taskunifier-app-linux
          path: |
            dist/latest-linux.yml
            dist/*.AppImage
            dist/*.tar.gz
            dist/*.snap

      - name: Upload Mac Artifacts
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: taskunifier-app-mac
          path: |
            dist/latest-mac.yml
            dist/*.dmg
            dist/*.dmg.blockmap

      - name: Upload Win Artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: taskunifier-app-win
          path: |
            dist/latest.yml
            dist/*.exe
            dist/*.exe.blockmap
